### ISSUE TITLE
generator-joomla-spc@0.0.6 requires a peer of yo@>=1.0.0 but none was installed.

### ISSUE THREAD

**Issue by FopherC** [pacav69/generator-joomla-spc#1]
When I try to install generator, the cli shows me:

![captura de pantalla de 2015-12-30 02-11-54](https://cloud.githubusercontent.com/assets/1615875/12048008/bd20978c-ae9a-11e5-8d35-39421c0dee45.png)

**Comment by pacav69** [comment]
There appears to be errors in the yo generator
Try this
npm install -g yo generator-joomla-spc

**Comment by pacav69** [comment]
updated readme.md and published v0.0.7
https://www.npmjs.com/package/generator-joomla-spc
